#Author: Felix KLeine Bösing
version: '2'

services:

  gymnotebook:
    build: .
    image: gymnotebook
    environment:
      - DISPLAY:$DISPLAY
    volumes:
    - ./src:/home/jovyan/work
    ports:
      - "8888:8888"