#Author: Felix KLeine Bösing
version: '2'

services:

  gymnotebook:
    build: .
    image: gymnotebook
    volumes:
    - ./src:/home/jovyan/work
    - ./data:/home/jovyan/work/data
    ports:
      - "127.0.0.1:8888:8888"